# Generated by Django 5.1.4 on 2024-12-12 01:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('minegocio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaccion',
            name='cantidad',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='vendedor',
            name='dni',
            field=models.PositiveIntegerField(unique=True),
        ),
    ]
